apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Client
metadata:
  name: simple-right
  namespace: test
spec:
  serverRef: "simple-deployment"
  configTo:
    name: "simplesshttt"
    namespace: "test"
  services:
  - name: "rathole-ssh"
    localAddr:
      host: "127.0.0.1"
      port: 22
    token:
      secretRef:
        name: "secret-name"
        key: "secret-key"
