apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Server
metadata:
  name: example-server
spec:
  bindAddr: "0.0.0.0:1234"
  exposeAddr: "server.example.com:1234"
  services:
    - bindAddr: "localhost:8080"
      noDelay: true
      token: "service-specific-token"
      type: tcp
  transport:
    noise:
      localPrivateKey: "Base64EncodedPrivateKey"
      pattern: "Noise_NK_25519_ChaChaPoly_BLAKE2s"
