---
spec:
  scope: Namespaced
  group: rathole.mrchypark.github.io
  names:
    kind: Client
    plural: clients
    singular: client
    shortNames:
      - cl
      - clt
  versions:
    - name: v1alpha1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
        openAPIV3Schema:
          properties:
            spec:
              properties:
                configTo:
                  properties:
                    name:
                      description: Name of the configration file name.
                      type: string
                    type:
                      default: secret
                      description: Type of configuration destination, currently only 'secret' is supported.
                      enum:
                        - secret
                      type: string
                  required:
                    - type
                    - name
                  type: object
                heartbeatTimeout:
                  default: 40
                  description: Specifies the heartbeat timeout in seconds. Default is 40.
                  type: integer
                retryInterval:
                  default: 1
                  description: Specifies the interval between retries in seconds. Default is 1.
                  type: integer
                serverRef:
                  description: Reference to the server. This field is required.
                  type: string
                services:
                  items:
                    properties:
                      localAddr:
                        description: Necessary. The address of the service that needs to be forwarded.
                        type: string
                      name:
                        description: Name of the service. This field is required.
                        type: string
                      nodelay:
                        default: true
                        description: Optional. Override the `client.transport.nodelay` per service.
                        type: boolean
                      retryInterval:
                        default: 1
                        description: Specifies the retry interval for the service in seconds. Default is 1. If not set, inherits the global config
                        type: number
                      token:
                        properties:
                          key:
                            description: Optional. Sets the service token directly.
                            type: string
                          secretRef:
                            properties:
                              key:
                                description: Key of the secret reference for token. Required if 'token' is specified.
                                type: string
                              name:
                                description: Name of the secret reference for token. Required if 'token' is specified.
                                type: string
                            type: object
                        type: object
                      type:
                        default: tcp
                        description: "Optional. The protocol that needs forwarding. Possible values: ['tcp', 'udp']. Default: tcp"
                        enum:
                          - tcp
                          - udp
                        type: string
                    required:
                      - name
                      - localAddr
                    type: object
                  type: array
              required:
                - serverRef
              type: object
          type: object
      storage: true
      subresources:
        status: {}
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
metadata:
  name: clients.rathole.mrchypark.github.io
  labels:
    k8s-app: rathole
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Namespaced
  group: rathole.mrchypark.github.io
  names:
    kind: Server
    plural: servers
    singular: server
    shortNames:
      - sv
      - svr
  versions:
    - name: v1alpha1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
        openAPIV3Schema:
          properties:
            spec:
              properties:
                bindAddr:
                  description: IP address must be a valid IPv4 address in the format of 0.0.0.0
                  properties:
                    ip:
                      default: 0.0.0.0
                      description: IP address must be a valid IPv4 address in the format of 0.0.0.0
                      pattern: ^(([0-9]{1,3}).){3}[0-9]{1,3}$
                      type: string
                    port:
                      default: 2333
                      description: Port number must be an integer between 0 and 65535.
                      format: int32
                      maximum: 65535
                      minimum: 0
                      type: integer
                  required:
                    - ip
                    - port
                  type: object
                defaultToken:
                  description: Optional. Global token for service.
                  properties:
                    key:
                      description: Optional. Sets the token directly.
                      type: string
                    secretRef:
                      description: Optional. Sets the secret reference
                      properties:
                        key:
                          description: Name of the key within the secret to be referenced.
                          type: string
                        name:
                          description: Name of the secret resource to be referenced.
                          type: string
                      type: object
                  type: object
                exposeAddr:
                  description: Specifies the address to be exposed. This must be set as required. Host:port.
                  properties:
                    addr:
                      description: Addr is host url for expose.
                      type: string
                    ip:
                      description: IP address must be a valid IPv4 address in the format of 0.0.0.0
                      pattern: ^(([0-9]{1,3}).){3}[0-9]{1,3}$
                      type: string
                    port:
                      default: 2333
                      description: Port number must be an integer between 0 and 65535.
                      format: int32
                      maximum: 65535
                      minimum: 0
                      type: integer
                  required:
                    - port
                  type: object
                heartbeatInterval:
                  default: 30
                  description: 'Optional. The interval between two application-layer heartbeat. Set to 0 to disable sending heartbeat. Default: 30 seconds.'
                  type: integer
                transport:
                  properties:
                    noise:
                      properties:
                        noisekeyLocal:
                          properties:
                            key:
                              description: Optional. Sets the noise key directly.
                              type: string
                            secretRef:
                              description: Optional. Sets the secret reference
                              properties:
                                key:
                                  description: Name of the key within the secret to be referenced.
                                  type: string
                                name:
                                  description: Name of the secret resource to be referenced.
                                  type: string
                              type: object
                          type: object
                        pattern:
                          default: Noise_NK_25519_ChaChaPoly_BLAKE2s
                          description: Noise protocol pattern. This field is optional.
                          type: string
                      type: object
                    type:
                      default: tcp
                      description: Transport type must be either 'tcp' or 'noise'.
                      enum:
                        - tcp
                        - noise
                      type: string
                  required:
                    - type
                  type: object
              required:
                - bindAddr
                - exposeAddr
                - transport
              type: object
          type: object
      storage: true
      subresources:
        status: {}
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
metadata:
  name: servers.rathole.mrchypark.github.io
  labels:
    k8s-app: rathole
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - '*'
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - '*'
  - resources:
      - events
    apiGroups:
      - events.k8s.io
    verbs:
      - '*'
  - resources:
      - clients
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - clients/status
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - servers
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - servers/status
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
  namespace: default
kind: ServiceAccount
apiVersion: v1

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: rathole
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: rathole
    kind: ServiceAccount
    namespace: default
