apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rathole-operator-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rathole.mrchypark.github.io"]
  resources: ["clients", "servers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rathole-operator-binding
subjects:
- kind: ServiceAccount
  name: rathole-operator-sa
roleRef:
  kind: ClusterRole
  name: rathole-operator-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rathole-operator-sa
