apiVersion: v1
kind: Service
metadata:
  name: rathole-operator-svc
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: rathole-operator
    app.kubernetes.io/name: rathole-operator
    app.kubernetes.io/instance: rathole-operator
