apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Client
metadata:
  name: simple-client
  namespace: test
spec:
  serverRef: "simple-server"
  services:
    - name: "rathole-ssh"
      localAddr: "127.0.0.1:22"
      token:
        secretRef:
          name: "secret-name"
          key: "secret-key"