apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Client
metadata:
  name: simple-client
  namespace: test
spec:
  serverRef: "simple-server"
  configTo:
    name: "simplessh"
    namespace: "test"
  services:
    - name: "rathole-ssh"
      localAddr: "127.0.0.1:22"
      token:
        secretRef:
          name: "secret-name"
          key: "secret-key"
---
apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Server
metadata:
  name: simple-server
  namespace: test
spec:
  bindAddr: "test"
  exposeAddr: "test2"
  transport:
    type: "noise"