apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rathole-system
commonLabels:
  name: rathole-operator
  app.kubernetes.io/name: rathole-operator
  app.kubernetes.io/instance: rathole-operator
commonAnnotations:
  provider: rathole-operator

resources:
- "./crd/crd.yaml"
- "./k8s/namespace.yaml"
- "./k8s/deployment.yaml"
- "./k8s/service.yaml"
- "./k8s/rbac.yaml"
