apiVersion: rathole.mrchypark.github.io/v1alpha1
kind: Client
metadata:
  name: example-client
  namespace: test
spec:
  serverRef: "example-server"
  configTo:
    name: "example-config-name"
    type: "secret"
  heartbeatTimeout: 40
  retryInterval: 1
  services:
    - name: "rich-ssh"
      localAddr: "127.0.0.1:22"
      type: "tcp"
      nodelay: true
      retryInterval: 1
      token:
        secretRef:
          name: "secret-name"
          key: "secret-key"
