---
spec:
  scope: Namespaced
  group: rathole.mrchypark.github.io
  names:
    kind: Client
    plural: clients
    singular: client
    shortNames:
      - cl
      - clt
  versions:
    - name: v1alpha1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
        openAPIV3Schema:
          properties:
            spec:
              properties:
                defaultToken:
                  default: default_token_if_not_specify
                  description: The default token of services, if they don't define their own ones. This field is optional.
                  type: string
                heartbeatTimeout:
                  default: 40
                  description: Set to 0 to disable the application-layer heartbeat test. This field is optional.
                  type: integer
                remoteAddr:
                  description: The address of the server. This field is necessary.
                  type: string
                retryInterval:
                  default: 1
                  description: The interval between retry to connect to the server. This field is optional.
                  type: integer
                services:
                  description: Services that need forwarding.
                  items:
                    properties:
                      localAddr:
                        description: The address of the service that needs to be forwarded. This field is necessary.
                        type: string
                      noDelay:
                        default: true
                        description: Override the `client.transport.noDelay` per service. This field is optional.
                        type: boolean
                      retryInterval:
                        default: 1
                        description: The interval between retry to connect to the server. This field is optional.
                        type: integer
                      token:
                        description: Token for the service. Necessary if `client.defaultToken` not set.
                        type: string
                      type:
                        default: tcp
                        description: The protocol that needs forwarding. This field is optional.
                        enum:
                          - tcp
                          - udp
                        type: string
                    type: object
                  type: array
                transport:
                  properties:
                    noise:
                      description: Noise protocol settings. See `docs/transport.md` for further explanation.
                      properties:
                        localPrivateKey:
                          description: Local private key, encoded in Base64. This field is optional.
                          type: string
                        pattern:
                          default: Noise_NK_25519_ChaChaPoly_BLAKE2s
                          description: Noise protocol pattern. This field is optional.
                          type: string
                        remotePublicKey:
                          description: Remote public key, encoded in Base64. This field is optional.
                          type: string
                      type: object
                    tcp:
                      description: TCP transport settings. This block also affects `noise` and `tls`.
                      properties:
                        keepaliveInterval:
                          default: 8
                          description: Specify `tcp_keepalive_intvl` in `tcp(7)`. This field is optional.
                          type: integer
                        keepaliveSecs:
                          default: 20
                          description: Specify `tcp_keepalive_time` in `tcp(7)`. This field is optional.
                          type: integer
                        noDelay:
                          default: true
                          description: Determine whether to enable TCP_NODELAY. This field is optional.
                          type: boolean
                        proxy:
                          description: The proxy used to connect to the server. `http` and `socks5` is supported. This field is optional.
                          type: string
                      type: object
                    type:
                      default: tcp
                      description: Specify which transport to use. This block is optional.
                      enum:
                        - tcp
                        - noise
                      type: string
                  type: object
              required:
                - remoteAddr
              type: object
          type: object
      storage: true
      subresources:
        status: {}
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
metadata:
  name: clients.rathole.mrchypark.github.io
  labels:
    k8s-app: rathole
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Namespaced
  group: rathole.mrchypark.github.io
  names:
    kind: Server
    plural: servers
    singular: server
    shortNames:
      - sv
      - svr
  versions:
    - name: v1alpha1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
        openAPIV3Schema:
          properties:
            spec:
              properties:
                bindAddr:
                  description: The address that the server listens for clients. This field is necessary.
                  type: string
                defaultToken:
                  description: The default token of services. This field is optional.
                  type: string
                exposeAddr:
                  description: The address of the server. This field is necessary.
                  type: string
                heartbeatInterval:
                  default: 30
                  description: The interval between two application-layer heartbeats. This field is optional.
                  type: integer
                services:
                  description: The services that the server exposes.
                  items:
                    properties:
                      bindAddr:
                        description: The address of the service is exposed at. This field is necessary.
                        type: string
                      noDelay:
                        default: true
                        description: Override the `server.transport.noDelay` per service. This field is optional.
                        type: boolean
                      token:
                        description: Token for the service. Necessary if `server.defaultToken` not set.
                        type: string
                      type:
                        default: tcp
                        description: The protocol of the service. This field is optional.
                        enum:
                          - tcp
                          - udp
                        type: string
                    type: object
                  type: array
                transport:
                  properties:
                    noise:
                      description: Noise protocol settings. See `https://github.com/rapiz1/rathole/blob/main/docs/transport.md` for further explanation.
                      properties:
                        localPrivateKey:
                          description: Local private key, encoded in Base64. This field is optional.
                          type: string
                        pattern:
                          default: Noise_NK_25519_ChaChaPoly_BLAKE2s
                          description: Noise protocol pattern. This field is optional.
                          type: string
                        remotePublicKey:
                          description: Remote public key, encoded in Base64. This field is optional.
                          type: string
                      type: object
                    tcp:
                      description: TCP transport settings.
                      properties:
                        keepaliveInterval:
                          default: 8
                          description: Specify `tcp_keepalive_intvl` in `tcp(7)`. This field is optional.
                          type: integer
                        keepaliveSecs:
                          default: 20
                          description: Specify `tcp_keepalive_time` in `tcp(7)`. This field is optional.
                          type: integer
                        noDelay:
                          default: true
                          description: Determine whether to enable TCP_NODELAY. This field is optional.
                          type: boolean
                      type: object
                    type:
                      default: tcp
                      description: Specify which transport to use. This field is optional.
                      enum:
                        - tcp
                        - noise
                      type: string
                  type: object
              required:
                - bindAddr
              type: object
          type: object
      storage: true
      subresources:
        status: {}
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
metadata:
  name: servers.rathole.mrchypark.github.io
  labels:
    k8s-app: rathole
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Namespaced
  group: rathole.mrchypark.github.io
  names:
    kind: NoiseKey
    plural: noisekeys
    singular: noisekey
    shortNames:
      - nk
      - nsk
  versions:
    - name: v1alpha1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
        openAPIV3Schema:
          properties:
            spec:
              properties:
                privateKeyField:
                  default: private
                  type: string
                publicKeyField:
                  default: public
                  type: string
                secretName:
                  type: string
              type: object
          type: object
      storage: true
      subresources:
        status: {}
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
metadata:
  name: noisekeys.rathole.mrchypark.github.io
  labels:
    k8s-app: rathole
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - '*'
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - '*'
  - resources:
      - events
    apiGroups:
      - events.k8s.io
    verbs:
      - '*'
  - resources:
      - clients
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - clients/status
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - noisekeys
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - noisekeys/status
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - servers
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'
  - resources:
      - servers/status
    apiGroups:
      - rathole.mrchypark.github.io
    verbs:
      - '*'

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
  namespace: default
kind: ServiceAccount
apiVersion: v1

---
metadata:
  name: rathole
  labels:
    k8s-app: rathole
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: rathole
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: rathole
    kind: ServiceAccount
    namespace: default
